### PR TITLE
required documents table

### PR DESCRIPTION
**Pull request by mind-adobe**
Kyc documents table

Fix #92 

Test URLs:
- Before: https://main--piramal--aemsites.hlx.page/home-loans
- After: https://issue-97-table--piramal--aemsites.hlx.page/home-loans

### CODE REVIEW

**Review by asthabh23 — CHANGES_REQUESTED** [review]
`Identity` and `Address` also need to be orange headings.

**Comment by mind-adobe** [comment]
@asthabh23 done

**Comment by asthabh23** [comment]
a lint issue exists for duplicate rule

**Comment by mind-adobe** [comment]
Fixed, forgot to push it before

**Comment by asthabh23** [comment]
@mind-adobe , `PAN card` text is shifted next to `Mandatory Documents`
can you pls recheck?
Screenshot 2024-08-05 at 18 49 36

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
