### PR TITLE
8 homepage columns block

### LINKED ISSUE #8: [Homepage] Columns Block
- [x] Variation 1 (desktop view)

Screenshot 2024-07-12 at 16 39 32

- [x] Variation 1 (Mobile view)

Screenshot 2024-07-12 at 16 40 46

- [x] Variation 2 (Desktop view):

Screenshot 2024-07-12 at 16 40 15

- [x] Variation 2 (Mobile view)

Screenshot 2024-07-12 at 16 41 19

- [x] Variation 2 - Just above footer
Mobile view:

Screenshot 2024-07-12 at 16 44 40

Desktop view:
Screenshot 2024-07-12 at 16 45 09

### PR DESCRIPTION
**Pull request by mind-adobe**
Added 2 variations for the column block:
badges + content-center/content-left

Fix #8 

Test URLs:
- Before: https://main--piramal--aemsites.hlx.page
- After: https://8-homepage-columns-block--piramal--aemsites.hlx.page

### CODE REVIEW

**Comment by asthabh23** [comment]
@mind-adobe , i do see fonts styling not matching upto the original site. maybe you need to see the font-weight and the font type used. (our version seems to have headings also different, can you please check again?)

Screenshot 2024-07-25 at 18 43 20

**Comment by asthabh23** [comment]
additionally, as we merge this PR into main, it would be great if we can have a final check on headings and section paddings and spacing. (since hero carousel is also now into main, so we can have a better look at the alignments - I will create a separate issue for this)

**Comment by mind-adobe** [comment]
> @mind-adobe , i do see fonts styling not matching upto the original site. maybe you need to see the font-weight and the font type used. (our version seems to have headings also different, can you please check again?)

About this I wanted to ask you. Should this be done through authoring (for example using a heading instead of a <p> tag) or should we just overwrite it in the code? I am not asking specifically for this issue, but in general

**Comment by mind-adobe** [comment]
@asthabh23 it should be fine now

**Comment by asthabh23** [comment]
@mind-adobe , can you please add some gap between the column cells. this will wrap the text also to look like what we have on original site
Screenshot 2024-07-26 at 13 52 16

**Comment by mind-adobe** [comment]
> @mind-adobe , can you please add some gap between the column cells. this will wrap the text also to look like what we have on original site
Done. Added bigger gaps between columns.

**Review by asthabh23 — APPROVED** [review]

**Pull request merged**
